package coreservlets.server;

import com.google.gwt.user.server.rpc.RemoteServiceServlet;

import coreservlets.client.*;

public class DataServiceImpl extends RemoteServiceServlet implements DataService {

  /** Generated by Eclipse. Useful for serialization. */
  private static final long serialVersionUID = 4860099427026709561L;

  @Override
  public String getButton1Data() {
    String result = String.format("Number: %.2f", Math.random() * 10);
    return (result);
  }

  @Override
  public String[] getButton2Data() {
    String[] results = { String.format("%.2f", Math.random()),
        String.format("%.2f", Math.random() * 10),
        String.format("%.2f", Math.random() * 100),
        String.format("%.2f", Math.random() * 1000) };
    return (results);
  }

  @Override
  public RandomNumber getButton3Data(String rangeString) {
    return (new RandomNumber(rangeString));
  }

  @Override
  public void logClientRandom(RandomNumber clientRandom) {
    log("Random number sent from client is: " + clientRandom.getValue());
    System.out.println("Random number '" + clientRandom.getValue()
        + "' was logged.");
  }
}
